def branchName="master"
def gitURL="https://github.com/cathenesi/temperature.git"
node('master'){
    try{
        stage('Iniciar build'){
            deleteDir()
        }

        stage('Baixar repositorio'){
            checkout scm        
        }

        stage('Build do projeto'){
            sh 'chmod 777 *'
            sh './gradle build'
            sh './gradle docker'
        }

        stage('Stop da aplicação em execucao'){
            sh 'sudo docker stop temperature'
        }

        stage('Start da nova versao'){
            dir('/home/ubuntu/github/temperature/build/docker'){
                sh 'sudo docker build --tag=temperature .' 
                sh 'sudo docker run -d --name temperature -p 9052:9052 temperature' 
            }
        }
    } catch (e) {
        throw e
    }         
}
