@Library('jenkins-library') _

def branchName="master"
def gitURL="https://github.com/cathenesi/temperature.git"
node('master'){
    try{
        stage('Iniciar build'){
            deleteDir()
        }

        stage('Clonar repositorio'){
            dir('/home/ubuntu/github/temperature'){
                sh 'sudo git stash' 
                sh 'sudo git pull' 
            }
        }

        stage('Build do projeto'){
            dir('/home/ubuntu/github/temperature'){
                sh 'sudo ./gradlew build'
                sh 'sudo ./gradlew docker'
            }
        }

        stage('Stop da aplicação em execucao'){
            sh 'sudo docker stop temperature'
        }

        stage('Start da nova versao'){
            dir('/home/ubuntu/github/temperature/build/docker'){
                sh 'sudo docker build --tag=temperature .' 
                sh 'sudo docker run -d --name temperature -p 9052:9052 temperature' 
            }
        }
    } catch (e) {
        throw e
    }         
}
