def branchName="master"
def gitURL="https://github.com/cathenesi/temperature.git"
node('master'){
    try{
        stage('Iniciar build'){
            deleteDir()
        }

        stage('Baixar repositorio'){
            checkout scm        
        }

        stage('Build do projeto'){
             sh 'sudo -n ./gradlew build' 
             sh 'sudo -n ./gradlew docker' 
        }

        stage('Stop da aplicação em execucao'){
            sh 'sudo -n docker stop temperature'
        }

        stage('Start da nova versao'){
            dir('/home/ubuntu/github/temperature/build/docker'){
                sh 'sudo -n docker build --tag=temperature .' 
                sh 'sudo -n docker run -d --name temperature -p 9052:9052 temperature' 
            }
        }
    } catch (e) {
        throw e
    }         
}
